name: Deploy Environment
on:
  workflow_dispatch:
    inputs:
      ls6_global_00:
        description: 'LS6 Global - 00'
        type: boolean
        required: false
      ls6_global_01:
        description: 'LS6 Global - 01'
        type: boolean
        required: false
      prod_global_00:
        description: 'Production Global - 00'
        type: boolean
        required: false
      prod_global_01:
        description: 'Production Global - 01'
        type: boolean
        required: false

jobs:
  prepare-matrix:
    runs-on: windows-latest
    outputs:
      environments: ${{ steps.set-matrix.outputs.environments }}
    steps:
      - id: set-matrix
        run: |
          $environments = @()
          if ("${{ inputs.ls6_global_00 }}" -eq "true") { $environments += "LS6 Global - 00" }
          if ("${{ inputs.ls6_global_01 }}" -eq "true") { $environments += "LS6 Global - 01" }
          if ("${{ inputs.prod_global_00 }}" -eq "true") { $environments += "Production Global - 00" }
          if ("${{ inputs.prod_global_01 }}" -eq "true") { $environments += "Production Global - 01" }
          # Output the selected environments as a JSON string
          $json = $environments | ConvertTo-Json -Compress
          echo "environments=$json" >> $env:GITHUB_OUTPUT
        shell: pwsh

  deploy:
    needs: prepare-matrix
    if: needs.prepare-matrix.outputs.environments != '[]'
    strategy:
      matrix:
        environment: ${{ fromJson(needs.prepare-matrix.outputs.environments) }}
      max-parallel: 2
      
    runs-on: windows-latest
    environment: ${{ matrix.environment }}

    steps:
      - uses: actions/checkout@v3

      - name: Install PowerShell-YAML Module
        shell: pwsh
        run: |
          Install-Module -Name powershell-yaml -Force -Scope CurrentUser
          Import-Module powershell-yaml

      - name: Process Variables
        shell: pwsh
        run: |
          ./fetch-vars.ps1 -environment "${{ matrix.environment }}"
