name: Deploy Environment
on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'Target Environments'
        required: true
        type: multi-select
        options:
          - "LS6 Global - 00"
          - "LS6 Global - 01"
          - "Production Global - 00"
          - "Production Global - 01"

jobs:
  deploy:
    strategy:
      matrix:
        environment: ${{ fromJSON(github.event.inputs.environments) }}
      max-parallel: 1  # This ensures sequential execution
    
    runs-on: windows-latest
    environment: ${{ matrix.environment }}

    steps:
      - uses: actions/checkout@v3

      - name: Install PowerShell-YAML Module
        shell: pwsh
        run: |
          Install-Module -Name powershell-yaml -Force -Scope CurrentUser

      - name: Consolidate Environment Variables
        id: consolidate_vars
        shell: pwsh
        run: |
          $environment = "${{ matrix.environment }}"
          # Rest of your consolidation script remains the same

      - name: Execute PowerShell Script
        shell: pwsh
        run: |
          Install-Module -Name powershell-yaml -Force -Scope CurrentUser
          Import-Module powershell-yaml
          ./fetch-vars.ps1 -environment "${{ matrix.environment }}"
