name: Deploy Environment
on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'Target Environments'
        required: true
        type: choice
        options:
          - "LS6 Global - 00"
          - "LS6 Global - 01"
          - "Production Global - 00"
          - "Production Global - 01"
        multiple: true

jobs:
  deploy:
    strategy:
      matrix:
        environment: ${{ fromJSON(github.event.inputs.environments) }}
      max-parallel: 2
      
    runs-on: windows-latest
    environment: ${{ matrix.environment }}

    steps:
      - uses: actions/checkout@v3

      - name: Install PowerShell-YAML Module
        shell: pwsh
        run: |
          Install-Module -Name powershell-yaml -Force -Scope CurrentUser
          Import-Module powershell-yaml

      - name: Process Variables
        shell: pwsh
        run: |
          ./fetch-vars.ps1 -environment "${{ matrix.environment }}"
